### ISSUE TITLE
domain:check avail can be  true/false

### ISSUE THREAD

**Issue by jcerdan** [getpinga/tembo#12]
Hi,

according to RFC 5731 domain check command returns an "avail"  attribute that can be 0/1 or false/true.
In your EPP class, domainCheck() function type casts avail attribut as an integer, but that fails if answer contains false/true.

```
$domains[$i]['avail'] = (int)$cd->name->attributes()->avail;
```
on line 1085 should be

```
$domains[$i]['avail'] = (string)$cd->name->attributes()->avail;
```

and then this should be parsed outside or maybe it should be converted to boolean in this function...

Edit: I'm currently using the 'Generic RFC EPP' against 'CORE/Knipp' Registrar.

**Comment by getpinga** [comment]
Hello,
Thanks for pointing this out.

https://github.com/getpinga/tembo/releases/tag/v0.8.1

Please check the current release, there it has been fixed.
