### ISSUE TITLE
13001 error

### ISSUE THREAD

**Issue by m4rek11** [getpinga/tembo#14]
Hello, 

i testing that EPP app for NASK (.pl domain) and for first time I got info from browser:
`Login Result: 1000: Command completed successfully`

but after refresh I always got error like:

```
 Command syntax error
                    13001
                xsd error - Unexpected EOF in prolog
 at [row,col {unknown-source}]: [1,0]
            IT4276027100
```

My index.php file is very simple and looks like:
```
<?php
    require_once 'vendor/pinga/tembo/examples/Connection.php';

    connectEpp('PL');
?>
```

I wiil be greatfull for any tips, thank you.

**Comment by getpinga** [comment]
Please check first the log directory , the response file, maybe there will be some hints.

**Comment by getpinga** [comment]
I'm seeing this issue from time to time only, trying to see is it from the .pl implementation or sth else

**Comment by getpinga** [comment]
To clear any issues, try `rm /tmp/eppcookie.txt` and then it seems error happens only when hello is used, or no command as in your case. All other commands work.

**Comment by m4rek11** [comment]
@getpinga, thank you for feedback.
