### ISSUE TITLE
epp error written while connecting to namingo registry 

### ISSUE THREAD

**Issue by anantsparrow** [getpinga/tembo#19]
Error : The stream or file "/www/wwwroot/sparrow.pw/vendor/pinga/tembo/src/../log/response-2024-06-16.log" could not be opened in append mode: Failed to open stream: Permission denied The exception occurred while attempting to log: Namingo EPP Server 1.0 2024-06-15T21:13:24.638Z 1.0 en urn:ietf:params:xml:ns:domain-1.0 urn:ietf:params:xml:ns:contact-1.0 urn:ietf:params:xml:ns:host-1.0 https://namingo.org/epp/funds-1.0 https://namingo.org/epp/identica-1.0 urn:ietf:params:xml:ns:secDNS-1.1 urn:ietf:params:xml:ns:rgp-1.0 urn:ietf:params:xml:ns:launch-1.0 urn:ietf:params:xml:ns:idn-1.0 urn:ietf:params:xml:ns:epp:fee-1.0 urn:ar:params:xml:ns:price-1.1 Error : Call to a member function domainCreate() on null

**Comment by getpinga** [comment]
This is file permission error, but please reopen an issue if you still have it.
