### ISSUE TITLE
hi there

### ISSUE THREAD

**Issue by anantsparrow** [getpinga/tembo#2]
do you have any solution to create own epp server for selling out slds domains,

just like it.com is doing?

**Comment by getpinga** [comment]
> do you have any solution to create own epp server for selling out slds domains,
> 
> just like it.com is doing?

Not yet, unfortunately. For now I'm working only on the client/billing side, and not the server/registry one. It will be much more complicated.

**Comment by anantsparrow** [comment]
https://cocca.org.nz/srs/ found this, can you try if you can install these

**Comment by getpinga** [comment]
Hello,
There are couple of available EPP servers - Cocca, Fred, etc.

For the moment I have no time to build such.
